"use client";

import PortalFooter from "@/components/PortalFooter";
import PortalMainNav from "@/components/PortalMainNav";
import PortalSideMenu from "@/components/PortalSideMenu";
import PortalTopStrip from "@/components/PortalTopStrip";
import {
  ApiError,
  fetchCourseTerms,
  fetchFilingSlip,
  fetchGradeReport,
  fetchMyStanding,
  type AcademicStatusType,
  type CourseTerm,
  type FilingSlipResponse,
  type GradeReportResponse,
  type StudentStandingResponse,
} from "@/lib/api";
import { useEffect, useMemo, useState } from "react";

const STATUS_META: Record<
  AcademicStatusType,
  { label: string; chip: string; tip: string }
> = {
  PROMOTED: {
    label: "Promoted",
    chip: "border-[#cae6cf] bg-[#ecf8ef] text-[#1f7a3a]",
    tip: "Good standing — clear to continue.",
  },
  WARNING: {
    label: "Warning",
    chip: "border-[#f0d9a0] bg-[#fff7e2] text-[#8a5a00]",
    tip: "Academic probation — one term to recover.",
  },
  DISMISSED: {
    label: "Dismissed",
    chip: "border-[#f0bcbc] bg-[#fdebeb] text-[#a31a1a]",
    tip: "Academic dismissal — GPA/failure thresholds breached.",
  },
  INCOMPLETE: {
    label: "Incomplete",
    chip: "border-[#cfddec] bg-[#eef4fa] text-[#1f5b94]",
    tip: "Held for review — an I/NG mark prevents a verdict.",
  },
  DISTINCTION: {
    label: "Distinction",
    chip: "border-[#cdbdf0] bg-[#f3edfb] text-[#5f3aa0]",
    tip: "Graduation classification.",
  },
};

function StatusChip({ status }: { status: AcademicStatusType }) {
  const m = STATUS_META[status];
  return (
    <span
      title={m.tip}
      className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-[11px] font-semibold uppercase tracking-[0.06em] ${m.chip}`}
    >
      {m.label}
    </span>
  );
}

function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : d.toLocaleDateString();
}

function fmtGpa(v: number | null | undefined): string {
  return v == null ? "—" : v.toFixed(2);
}

function esc(s: unknown): string {
  return String(s ?? "").replace(/[&<>"]/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] as string),
  );
}

/** Open a printable window with the given title + body HTML and trigger print. */
function printDocument(title: string, bodyHtml: string) {
  const w = window.open("", "_blank", "width=820,height=1000");
  if (!w) {
    alert("Pop-up blocked. Allow pop-ups to download this document.");
    return;
  }
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title>
    <style>
      *{box-sizing:border-box} body{font-family:Arial,Helvetica,sans-serif;color:#1a1a1a;margin:0;padding:32px;font-size:13px}
      h1{font-size:20px;margin:0 0 2px} .muted{color:#5a5a5a}
      .head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #1f6fb3;padding-bottom:12px;margin-bottom:16px}
      .grid{display:grid;grid-template-columns:1fr 1fr;gap:6px 24px;margin:12px 0}
      .grid div span{color:#5a5a5a} table{width:100%;border-collapse:collapse;margin-top:12px}
      th,td{text-align:left;padding:7px 10px;border-bottom:1px solid #e2e2e2;font-size:12.5px}
      th{background:#f1f5f9;text-transform:uppercase;font-size:10.5px;letter-spacing:.05em;color:#5a5a5a}
      .totals{margin-top:14px;font-weight:bold} .chip{display:inline-block;border:1px solid #ccc;border-radius:999px;padding:2px 10px;font-size:11px;font-weight:bold}
      .foot{margin-top:28px;color:#8a8a8a;font-size:10.5px;border-top:1px solid #e2e2e2;padding-top:10px}
      @media print{body{padding:0}}
    </style></head><body>${bodyHtml}
    <div class="foot">Document ID for reference only. Generated by the AAU Registrar portal. This is not an officially sealed transcript.</div>
    <script>window.onload=function(){window.print()}</script></body></html>`);
  w.document.close();
}

function gradeReportHtml(r: GradeReportResponse): string {
  const rows = r.courses
    .map(
      (c) =>
        `<tr><td>${esc(c.course_code)}</td><td>${esc(c.course_title)}</td><td>${c.credit_hours}</td><td>${esc(c.letter_grade)}</td><td>${c.grade_points ?? "—"}</td></tr>`,
    )
    .join("");
  const status = r.academic_status ? STATUS_META[r.academic_status]?.label ?? r.academic_status : "—";
  return `
    <div class="head">
      <div><h1>Official Grade Report</h1><div class="muted">${esc(r.term.term_name)} · Phase ${esc(r.term.term_phase)}</div></div>
      <div class="muted" style="text-align:right">Doc: ${esc(r.document_id).slice(0, 8)}<br/>${fmtDate(r.generated_at)}</div>
    </div>
    <div class="grid">
      <div><span>Student:</span> <b>${esc(r.student.full_name)}</b></div>
      <div><span>ID:</span> ${esc(r.student.student_number)}</div>
      <div><span>Department:</span> ${esc(r.student.department)}</div>
      <div><span>Semester:</span> ${r.student.current_semester}</div>
    </div>
    <table><thead><tr><th>Code</th><th>Course</th><th>Cr</th><th>Grade</th><th>Points</th></tr></thead><tbody>${rows}</tbody></table>
    <div class="totals">Term GPA: ${fmtGpa(r.term_gpa)} &nbsp;·&nbsp; CGPA: ${fmtGpa(r.cumulative_gpa)} &nbsp;·&nbsp; Term credits: ${r.term_credit_hours} &nbsp;·&nbsp; Cumulative: ${r.cumulative_credit_hours}</div>
    <p style="margin-top:14px"><span class="chip">Academic status: ${esc(status)}</span></p>
    ${r.explanation ? `<p class="muted" style="margin-top:8px">${esc(r.explanation)}</p>` : ""}`;
}

function filingSlipHtml(r: FilingSlipResponse): string {
  const rows = r.courses
    .map(
      (c) =>
        `<tr><td>${esc(c.course_code)}</td><td>${esc(c.course_title)}</td><td>${c.credit_hours}</td><td>${c.is_dropped ? "Dropped" : "Active"}</td></tr>`,
    )
    .join("");
  return `
    <div class="head">
      <div><h1>Registration Filing Slip</h1><div class="muted">${esc(r.term.term_name)} · Phase ${esc(r.term.term_phase)}</div></div>
      <div class="muted" style="text-align:right">Doc: ${esc(r.document_id).slice(0, 8)}<br/>${fmtDate(r.generated_at)}</div>
    </div>
    <div class="grid">
      <div><span>Student:</span> <b>${esc(r.student.full_name)}</b></div>
      <div><span>ID:</span> ${esc(r.student.student_number)}</div>
      <div><span>Department:</span> ${esc(r.student.department)}</div>
      <div><span>Section:</span> ${esc(r.section_code ?? "—")}</div>
      <div><span>Status:</span> ${esc(r.registration_status)}</div>
      <div><span>Sponsorship:</span> ${esc(r.sponsorship_type)}</div>
      <div><span>Payment ref:</span> ${esc(r.payment_reference ?? "Unpaid")}</div>
      <div><span>Finalised:</span> ${fmtDate(r.finalised_at)}</div>
    </div>
    <table><thead><tr><th>Code</th><th>Course</th><th>Cr</th><th>State</th></tr></thead><tbody>${rows}</tbody></table>
    <div class="totals">Active credit hours: ${r.total_credit_hours}</div>
    ${r.last_authorised_status ? `<p class="muted" style="margin-top:10px">Carry-over standing: <b>${esc(r.last_authorised_status)}</b> (${esc(r.last_authorised_term_name ?? "previous term")})</p>` : ""}`;
}

function formatPhase(phase: string): string {
  if (!phase) return phase;
  return phase.charAt(0).toUpperCase() + phase.slice(1).toLowerCase();
}

export default function AcademicStandingPage() {
  const [standing, setStanding] = useState<StudentStandingResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [busyDoc, setBusyDoc] = useState<string | null>(null);
  const [docError, setDocError] = useState<string | null>(null);

  const [terms, setTerms] = useState<CourseTerm[]>([]);
  const [filingTerm, setFilingTerm] = useState<string>("");

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    fetchMyStanding()
      .then((d) => {
        if (!cancelled) setStanding(d);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        if (err instanceof ApiError && err.status === 403) {
          setError("Only enrolled students can view academic standing.");
        } else if (err instanceof ApiError) {
          setError(err.message || `Could not load standing (HTTP ${err.status}).`);
        } else {
          setError("Could not load academic standing.");
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    fetchCourseTerms()
      .then((rows) => {
        if (cancelled) return;
        setTerms(rows);
        const open = rows.find((t) => t.is_open) ?? rows[0];
        if (open) setFilingTerm(open.id);
      })
      .catch(() => {
        /* term picker optional */
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const current = standing?.current_status ?? null;

  async function downloadGradeReport(termId: string) {
    setBusyDoc(`gr-${termId}`);
    setDocError(null);
    try {
      const r = await fetchGradeReport(termId);
      printDocument(`Grade Report — ${r.term.term_name}`, gradeReportHtml(r));
    } catch (err) {
      setDocError(
        err instanceof ApiError && err.status === 404
          ? "Grade report isn't available until this term's standing is authorised."
          : err instanceof Error
            ? err.message
            : "Could not generate the grade report.",
      );
    } finally {
      setBusyDoc(null);
    }
  }

  async function downloadFilingSlip() {
    if (!filingTerm) return;
    setBusyDoc("fs");
    setDocError(null);
    try {
      const r = await fetchFilingSlip(filingTerm);
      printDocument(`Filing Slip — ${r.term.term_name}`, filingSlipHtml(r));
    } catch (err) {
      setDocError(
        err instanceof ApiError && err.status === 404
          ? "No registration found for that term, so there's no filing slip."
          : err instanceof Error
            ? err.message
            : "Could not generate the filing slip.",
      );
    } finally {
      setBusyDoc(null);
    }
  }

  const filingTermLabel = useMemo(() => {
    const t = terms.find((x) => x.id === filingTerm);
    return t ? `${t.term_name} · ${formatPhase(t.phase)}` : "";
  }, [terms, filingTerm]);

  return (
    <div className="flex min-h-screen flex-col bg-[#ffffff] font-[Arial,Helvetica,sans-serif] text-[16px] text-[#1a1a1a]">
      <PortalTopStrip />
      <PortalMainNav />
      <main className="flex-1 py-[8px] md:pr-[60px]">
        <div className="flex flex-col gap-5 md:flex-row">
          <PortalSideMenu />
          <section className="flex-1 md:ml-[40px]">
            <div className="px-3 py-1 text-[16px] md:px-2">
              <div className="md:max-w-[1080px]">
                <h1 className="mb-2 border-b border-[#e0e0e0] pb-2 text-[22px] font-semibold text-[#222] md:text-[24px]">
                  Academic Standing
                </h1>

                {loading ? (
                  <div className="mt-4 flex flex-col items-center gap-3 rounded-lg border border-dashed border-[#cfddec] bg-[#f6f9fc] py-12">
                    <div className="h-10 w-10 animate-spin rounded-full border-2 border-[#cfddec] border-t-[#2f78b7]" />
                    <p className="text-[13px] text-[#5a5a5a]">Loading academic standing…</p>
                  </div>
                ) : error ? (
                  <p className="mt-4 rounded-lg border border-[#f0bcbc] bg-[#fdebeb] px-4 py-6 text-center text-[14px] font-semibold text-[#a31a1a]">
                    {error}
                  </p>
                ) : (
                  <>
                    {/* Current status banner */}
                    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-gray-200 bg-[linear-gradient(180deg,#f8fbff_0%,#eef4fa_100%)] p-4 shadow-sm md:p-5">
                      <div>
                        <p className="text-[12px] font-semibold uppercase tracking-[0.1em] text-[#5a5a5a]">
                          Current standing
                        </p>
                        <div className="mt-1.5 flex items-center gap-3">
                          {current ? (
                            <StatusChip status={current} />
                          ) : (
                            <span className="text-[14px] text-[#5a5a5a]">
                              No authorised standing yet.
                            </span>
                          )}
                          <span className="text-[13px] text-[#3a3a3a]">
                            {standing?.full_name} · {standing?.student_number}
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* Filing slip (current/upcoming term) */}
                    <div className="mt-4 rounded-xl border border-gray-200 bg-white p-4 shadow-sm md:p-5">
                      <p className="text-[13px] font-semibold text-[#1f2f40]">
                        Registration filing slip
                      </p>
                      <p className="mt-0.5 text-[12px] text-[#5a5a5a]">
                        Proof of registration for the current/upcoming term.
                      </p>
                      <div className="mt-3 flex flex-wrap items-end gap-3">
                        <div>
                          <label className="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-[#5a5a5a]">
                            Term
                          </label>
                          <select
                            value={filingTerm}
                            onChange={(e) => setFilingTerm(e.target.value)}
                            disabled={terms.length === 0}
                            className="h-[36px] w-[260px] rounded-md border border-[#9bb0cc] bg-white px-3 text-[13px] outline-none disabled:opacity-60"
                          >
                            {terms.length === 0 ? (
                              <option value="">No terms available</option>
                            ) : null}
                            {terms.map((t) => (
                              <option key={t.id} value={t.id}>
                                {t.term_name} · {formatPhase(t.phase)}
                                {t.is_open ? " · open" : ""}
                              </option>
                            ))}
                          </select>
                        </div>
                        <button
                          type="button"
                          onClick={() => void downloadFilingSlip()}
                          disabled={!filingTerm || busyDoc === "fs"}
                          className="h-[36px] rounded-md bg-[#3f79b5] px-4 text-[13px] font-semibold text-white hover:bg-[#356e9f] disabled:opacity-60"
                        >
                          {busyDoc === "fs" ? "Preparing…" : "Download filing slip"}
                        </button>
                      </div>
                    </div>

                    {docError ? (
                      <p className="mt-3 rounded-md border border-[#f0bcbc] bg-[#fdebeb] px-3 py-2 text-[12px] text-[#a31a1a]">
                        {docError}
                      </p>
                    ) : null}

                    {/* Per-term standing cards */}
                    <h2 className="mt-6 text-[15px] font-semibold text-[#1f2f40]">
                      Standing by term
                    </h2>
                    {standing && standing.terms.length > 0 ? (
                      <div className="mt-3 space-y-3">
                        {standing.terms.map((t) => (
                          <div
                            key={t.id}
                            className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"
                          >
                            <div className="flex flex-wrap items-center justify-between gap-3">
                              <div className="flex flex-wrap items-center gap-2.5">
                                <span className="text-[14px] font-semibold text-[#1f2f40]">
                                  {t.term_name}
                                </span>
                                <span className="text-[12px] text-[#5a5a5a]">
                                  Phase {formatPhase(t.term_phase)}
                                </span>
                                <StatusChip status={t.status} />
                              </div>
                              <button
                                type="button"
                                onClick={() => void downloadGradeReport(t.term_id)}
                                disabled={busyDoc === `gr-${t.term_id}`}
                                className="h-[32px] rounded-md border border-[#9bb0cc] bg-white px-3 text-[12px] font-semibold text-[#2f76b7] hover:bg-[#eef4ff] disabled:opacity-60"
                              >
                                {busyDoc === `gr-${t.term_id}` ? "Preparing…" : "Grade report"}
                              </button>
                            </div>
                            <div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-[12.5px] text-[#3a3a3a]">
                              <span>SGPA <b>{fmtGpa(t.sgpa)}</b></span>
                              <span>CGPA <b>{fmtGpa(t.cgpa)}</b></span>
                              <span>Term credits {t.term_credit_hours}</span>
                              <span>Cumulative {t.cumulative_credit_hours}</span>
                              {t.f_count_term > 0 ? (
                                <span className="text-[#a31a1a]">F count {t.f_count_term}</span>
                              ) : null}
                              <span className="text-[#5a5a5a]">
                                Authorised {fmtDate(t.authorised_at)}
                              </span>
                            </div>
                            {t.explanation ? (
                              <p className="mt-2 rounded-md bg-[#f6f9fc] px-3 py-2 text-[12.5px] text-[#3a3a3a]">
                                {t.explanation}
                              </p>
                            ) : null}
                          </div>
                        ))}
                      </div>
                    ) : (
                      <p className="mt-3 rounded-lg border border-dashed border-[#cfddec] bg-[#f6f9fc] px-4 py-8 text-center text-[13px] text-[#5a5a5a]">
                        No authorised standings yet. Your status appears here once the
                        department head authorises a term&apos;s grades.
                        {filingTermLabel ? ` Filing slip available for ${filingTermLabel}.` : ""}
                      </p>
                    )}
                  </>
                )}
              </div>
            </div>
          </section>
        </div>
      </main>
      <PortalFooter />
    </div>
  );
}
