"use client";

import PortalFooter from "@/components/PortalFooter";
import PortalMainNav from "@/components/PortalMainNav";
import PortalSideMenu from "@/components/PortalSideMenu";
import PortalTopStrip from "@/components/PortalTopStrip";
import {
  ApiError,
  fetchCourseTerms,
  fetchFilingSlip,
  fetchGradeReport,
  fetchMyStanding,
  type AcademicStatusType,
  type CourseTerm,
  type FilingSlipResponse,
  type GradeReportResponse,
  type StudentStandingResponse,
} from "@/lib/api";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useEffect, useMemo, useState } from "react";

const STATUS_META: Record<
  AcademicStatusType,
  { label: string; chip: string; tip: string }
> = {
  PROMOTED: {
    label: "Promoted",
    chip: "border-[#cae6cf] bg-[#ecf8ef] text-[#1f7a3a]",
    tip: "Good standing — clear to continue.",
  },
  WARNING: {
    label: "Warning",
    chip: "border-[#f0d9a0] bg-[#fff7e2] text-[#8a5a00]",
    tip: "Academic probation — one term to recover.",
  },
  DISMISSED: {
    label: "Dismissed",
    chip: "border-[#f0bcbc] bg-[#fdebeb] text-[#a31a1a]",
    tip: "Academic dismissal — GPA/failure thresholds breached.",
  },
  INCOMPLETE: {
    label: "Incomplete",
    chip: "border-[#cfddec] bg-[#eef4fa] text-[#1f5b94]",
    tip: "Held for review — an I/NG mark prevents a verdict.",
  },
  DISTINCTION: {
    label: "Distinction",
    chip: "border-[#cdbdf0] bg-[#f3edfb] text-[#5f3aa0]",
    tip: "Graduation classification.",
  },
};

function StatusChip({ status }: { status: AcademicStatusType }) {
  const m = STATUS_META[status];
  return (
    <span
      title={m.tip}
      className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-[11px] font-semibold uppercase tracking-[0.06em] ${m.chip}`}
    >
      {m.label}
    </span>
  );
}

function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : d.toLocaleDateString();
}

function fmtGpa(v: number | null | undefined): string {
  return v == null ? "—" : v.toFixed(2);
}

function slugify(s: string): string {
  return String(s ?? "document")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    || "document";
}

// ── PDF generators ──────────────────────────────────────────────
// Both records are rendered with jsPDF + jspdf-autotable. The PDF
// lands directly in the browser's downloads folder via doc.save() —
// no print dialog, no new tab. Layout is intentionally minimal so the
// file prints well on both A4 and US Letter.

const PDF_FOOTER =
  "Document ID for reference only. Generated by the AAU Registrar portal. This is not an officially sealed transcript.";

/** Draw the shared header block (title + term info + doc id + date). */
function drawDocHeader(
  doc: jsPDF,
  heading: string,
  subheading: string,
  documentId: string,
  generatedAt: string,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor("#1f2f40");
  doc.text(heading, 40, 50);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor("#5a5a5a");
  doc.text(subheading, 40, 68);

  // Right-aligned doc id + date
  doc.setFontSize(9);
  const docId = `Doc: ${String(documentId).slice(0, 8)}`;
  const dateStr = fmtDate(generatedAt);
  doc.text(docId, pageWidth - 40, 50, { align: "right" });
  doc.text(dateStr, pageWidth - 40, 64, { align: "right" });

  // Header underline
  doc.setDrawColor("#1f6fb3");
  doc.setLineWidth(1.5);
  doc.line(40, 80, pageWidth - 40, 80);

  return 96; // y position the caller can continue drawing from
}

/** Draw a 2-column key/value grid for header fields. Returns the next y. */
function drawKeyValueGrid(
  doc: jsPDF,
  pairs: Array<[string, string]>,
  startY: number,
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const colWidth = (pageWidth - 80) / 2;
  const lineHeight = 16;
  doc.setFontSize(10);

  let y = startY;
  pairs.forEach((pair, idx) => {
    const col = idx % 2;
    const x = 40 + col * colWidth;

    doc.setFont("helvetica", "normal");
    doc.setTextColor("#5a5a5a");
    doc.text(`${pair[0]}:`, x, y);
    const labelWidth = doc.getTextWidth(`${pair[0]}: `);

    doc.setFont("helvetica", "bold");
    doc.setTextColor("#1f2f40");
    doc.text(pair[1] || "—", x + labelWidth, y);

    if (col === 1) y += lineHeight;
  });
  // If odd number of pairs, advance one more row.
  if (pairs.length % 2 === 1) y += lineHeight;
  return y + 4;
}

/** Drop the small grey footer line at the bottom of the page. */
function drawDocFooter(doc: jsPDF): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setDrawColor("#e2e2e2");
  doc.setLineWidth(0.5);
  doc.line(40, pageHeight - 48, pageWidth - 40, pageHeight - 48);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor("#8a8a8a");
  doc.text(PDF_FOOTER, 40, pageHeight - 32, {
    maxWidth: pageWidth - 80,
  });
}

function downloadGradeReportPdf(r: GradeReportResponse, filename: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  let y = drawDocHeader(
    doc,
    "Official Grade Report",
    `${r.term.term_name} · Phase ${r.term.term_phase}`,
    r.document_id,
    r.generated_at,
  );

  y = drawKeyValueGrid(
    doc,
    [
      ["Student", r.student.full_name],
      ["ID", r.student.student_number],
      ["Department", r.student.department],
      ["Semester", String(r.student.current_semester)],
    ],
    y,
  );

  autoTable(doc, {
    startY: y,
    head: [["Code", "Course", "Cr", "Grade", "Points"]],
    body: r.courses.map((c) => [
      c.course_code,
      c.course_title,
      String(c.credit_hours),
      c.letter_grade,
      c.grade_points == null ? "—" : String(c.grade_points),
    ]),
    styles: { font: "helvetica", fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: [241, 245, 249], textColor: 90, fontStyle: "bold" },
    columnStyles: {
      0: { cellWidth: 70 },
      2: { halign: "right", cellWidth: 36 },
      3: { halign: "center", cellWidth: 56 },
      4: { halign: "right", cellWidth: 56 },
    },
    margin: { left: 40, right: 40 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const afterTableY = (doc as any).lastAutoTable?.finalY ?? y;
  let cursor = afterTableY + 18;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor("#1f2f40");
  doc.text(
    `Term GPA: ${fmtGpa(r.term_gpa)}   ·   CGPA: ${fmtGpa(r.cumulative_gpa)}   ·   Term credits: ${r.term_credit_hours}   ·   Cumulative: ${r.cumulative_credit_hours}`,
    40,
    cursor,
  );
  cursor += 22;

  const status = r.academic_status
    ? STATUS_META[r.academic_status]?.label ?? r.academic_status
    : "—";
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor("#1f2f40");
  doc.text(`Academic status:  ${status}`, 40, cursor);
  cursor += 18;

  if (r.explanation) {
    doc.setFontSize(9);
    doc.setTextColor("#5a5a5a");
    const lines = doc.splitTextToSize(r.explanation, doc.internal.pageSize.getWidth() - 80);
    doc.text(lines, 40, cursor);
  }

  drawDocFooter(doc);
  doc.save(filename);
}

function downloadFilingSlipPdf(r: FilingSlipResponse, filename: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  let y = drawDocHeader(
    doc,
    "Registration Filing Slip",
    `${r.term.term_name} · Phase ${r.term.term_phase}`,
    r.document_id,
    r.generated_at,
  );

  y = drawKeyValueGrid(
    doc,
    [
      ["Student", r.student.full_name],
      ["ID", r.student.student_number],
      ["Department", r.student.department],
      ["Section", r.section_code ?? "—"],
      ["Status", r.registration_status],
      ["Sponsorship", r.sponsorship_type],
      ["Payment ref", r.payment_reference ?? "Unpaid"],
      ["Finalised", fmtDate(r.finalised_at)],
    ],
    y,
  );

  autoTable(doc, {
    startY: y,
    head: [["Code", "Course", "Cr", "State"]],
    body: r.courses.map((c) => [
      c.course_code,
      c.course_title,
      String(c.credit_hours),
      c.is_dropped ? "Dropped" : "Active",
    ]),
    styles: { font: "helvetica", fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: [241, 245, 249], textColor: 90, fontStyle: "bold" },
    columnStyles: {
      0: { cellWidth: 70 },
      2: { halign: "right", cellWidth: 36 },
      3: { halign: "center", cellWidth: 60 },
    },
    margin: { left: 40, right: 40 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const afterTableY = (doc as any).lastAutoTable?.finalY ?? y;
  let cursor = afterTableY + 18;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor("#1f2f40");
  doc.text(`Active credit hours: ${r.total_credit_hours}`, 40, cursor);
  cursor += 18;

  if (r.last_authorised_status) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor("#5a5a5a");
    doc.text(
      `Carry-over standing: ${r.last_authorised_status} (${r.last_authorised_term_name ?? "previous term"})`,
      40,
      cursor,
    );
  }

  drawDocFooter(doc);
  doc.save(filename);
}

function formatPhase(phase: string): string {
  if (!phase) return phase;
  return phase.charAt(0).toUpperCase() + phase.slice(1).toLowerCase();
}

export default function AcademicStandingPage() {
  const [standing, setStanding] = useState<StudentStandingResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [busyDoc, setBusyDoc] = useState<string | null>(null);
  const [docError, setDocError] = useState<string | null>(null);

  const [terms, setTerms] = useState<CourseTerm[]>([]);
  const [filingTerm, setFilingTerm] = useState<string>("");

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    fetchMyStanding()
      .then((d) => {
        if (!cancelled) setStanding(d);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        if (err instanceof ApiError && err.status === 403) {
          setError("Only enrolled students can view academic standing.");
        } else if (err instanceof ApiError) {
          setError(err.message || `Could not load standing (HTTP ${err.status}).`);
        } else {
          setError("Could not load academic standing.");
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    fetchCourseTerms()
      .then((rows) => {
        if (cancelled) return;
        setTerms(rows);
        const open = rows.find((t) => t.is_open) ?? rows[0];
        if (open) setFilingTerm(open.id);
      })
      .catch(() => {
        /* term picker optional */
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const current = standing?.current_status ?? null;

  async function downloadGradeReport(termId: string) {
    setBusyDoc(`gr-${termId}`);
    setDocError(null);
    try {
      const r = await fetchGradeReport(termId);
      downloadGradeReportPdf(r, `grade-report-${slugify(r.term.term_name)}.pdf`);
    } catch (err) {
      setDocError(
        err instanceof ApiError && err.status === 404
          ? "Grade report isn't available until this term's standing is authorised."
          : err instanceof Error
            ? err.message
            : "Could not generate the grade report.",
      );
    } finally {
      setBusyDoc(null);
    }
  }

  async function downloadFilingSlip() {
    if (!filingTerm) return;
    setBusyDoc("fs");
    setDocError(null);
    try {
      const r = await fetchFilingSlip(filingTerm);
      downloadFilingSlipPdf(r, `filing-slip-${slugify(r.term.term_name)}.pdf`);
    } catch (err) {
      setDocError(
        err instanceof ApiError && err.status === 404
          ? "No registration found for that term, so there's no filing slip."
          : err instanceof Error
            ? err.message
            : "Could not generate the filing slip.",
      );
    } finally {
      setBusyDoc(null);
    }
  }

  const filingTermLabel = useMemo(() => {
    const t = terms.find((x) => x.id === filingTerm);
    return t ? `${t.term_name} · ${formatPhase(t.phase)}` : "";
  }, [terms, filingTerm]);

  return (
    <div className="flex min-h-screen flex-col bg-[#ffffff] font-[Arial,Helvetica,sans-serif] text-[16px] text-[#1a1a1a]">
      <PortalTopStrip />
      <PortalMainNav />
      <main className="flex-1 py-[8px] md:pr-[60px]">
        <div className="flex flex-col gap-5 md:flex-row">
          <PortalSideMenu />
          <section className="flex-1 md:ml-[40px]">
            <div className="px-3 py-1 text-[16px] md:px-2">
              <div className="md:max-w-[1080px]">
                <h1 className="mb-2 border-b border-[#e0e0e0] pb-2 text-[22px] font-semibold text-[#222] md:text-[24px]">
                  Academic Standing
                </h1>

                {loading ? (
                  <div className="mt-4 flex flex-col items-center gap-3 rounded-lg border border-dashed border-[#cfddec] bg-[#f6f9fc] py-12">
                    <div className="h-10 w-10 animate-spin rounded-full border-2 border-[#cfddec] border-t-[#2f78b7]" />
                    <p className="text-[13px] text-[#5a5a5a]">Loading academic standing…</p>
                  </div>
                ) : error ? (
                  <p className="mt-4 rounded-lg border border-[#f0bcbc] bg-[#fdebeb] px-4 py-6 text-center text-[14px] font-semibold text-[#a31a1a]">
                    {error}
                  </p>
                ) : (
                  <>
                    {/* Current status banner */}
                    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-gray-200 bg-[linear-gradient(180deg,#f8fbff_0%,#eef4fa_100%)] p-4 shadow-sm md:p-5">
                      <div>
                        <p className="text-[12px] font-semibold uppercase tracking-[0.1em] text-[#5a5a5a]">
                          Current standing
                        </p>
                        <div className="mt-1.5 flex items-center gap-3">
                          {current ? (
                            <StatusChip status={current} />
                          ) : (
                            <span className="text-[14px] text-[#5a5a5a]">
                              No authorised standing yet.
                            </span>
                          )}
                          <span className="text-[13px] text-[#3a3a3a]">
                            {standing?.full_name} · {standing?.student_number}
                          </span>
                        </div>
                      </div>
                    </div>

                    {/* Filing slip (current/upcoming term) */}
                    <div className="mt-4 rounded-xl border border-gray-200 bg-white p-4 shadow-sm md:p-5">
                      <p className="text-[13px] font-semibold text-[#1f2f40]">
                        Registration filing slip
                      </p>
                      <p className="mt-0.5 text-[12px] text-[#5a5a5a]">
                        Proof of registration for the current/upcoming term.
                      </p>
                      <div className="mt-3 flex flex-wrap items-end gap-3">
                        <div>
                          <label className="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-[#5a5a5a]">
                            Term
                          </label>
                          <select
                            value={filingTerm}
                            onChange={(e) => setFilingTerm(e.target.value)}
                            disabled={terms.length === 0}
                            className="h-[36px] w-[260px] rounded-md border border-[#9bb0cc] bg-white px-3 text-[13px] outline-none disabled:opacity-60"
                          >
                            {terms.length === 0 ? (
                              <option value="">No terms available</option>
                            ) : null}
                            {terms.map((t) => (
                              <option key={t.id} value={t.id}>
                                {t.term_name} · {formatPhase(t.phase)}
                                {t.is_open ? " · open" : ""}
                              </option>
                            ))}
                          </select>
                        </div>
                        <button
                          type="button"
                          onClick={() => void downloadFilingSlip()}
                          disabled={!filingTerm || busyDoc === "fs"}
                          className="h-[36px] rounded-md bg-[#3f79b5] px-4 text-[13px] font-semibold text-white hover:bg-[#356e9f] disabled:opacity-60"
                        >
                          {busyDoc === "fs" ? "Preparing…" : "Download filing slip"}
                        </button>
                      </div>
                    </div>

                    {docError ? (
                      <p className="mt-3 rounded-md border border-[#f0bcbc] bg-[#fdebeb] px-3 py-2 text-[12px] text-[#a31a1a]">
                        {docError}
                      </p>
                    ) : null}

                    {/* Per-term standing cards */}
                    <h2 className="mt-6 text-[15px] font-semibold text-[#1f2f40]">
                      Standing by term
                    </h2>
                    {standing && standing.terms.length > 0 ? (
                      <div className="mt-3 space-y-3">
                        {standing.terms.map((t) => (
                          <div
                            key={t.id}
                            className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm"
                          >
                            <div className="flex flex-wrap items-center justify-between gap-3">
                              <div className="flex flex-wrap items-center gap-2.5">
                                <span className="text-[14px] font-semibold text-[#1f2f40]">
                                  {t.term_name}
                                </span>
                                <span className="text-[12px] text-[#5a5a5a]">
                                  Phase {formatPhase(t.term_phase)}
                                </span>
                                <StatusChip status={t.status} />
                              </div>
                              <button
                                type="button"
                                onClick={() => void downloadGradeReport(t.term_id)}
                                disabled={busyDoc === `gr-${t.term_id}`}
                                className="h-[32px] rounded-md border border-[#9bb0cc] bg-white px-3 text-[12px] font-semibold text-[#2f76b7] hover:bg-[#eef4ff] disabled:opacity-60"
                              >
                                {busyDoc === `gr-${t.term_id}` ? "Preparing…" : "Grade report"}
                              </button>
                            </div>
                            <div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-[12.5px] text-[#3a3a3a]">
                              <span>SGPA <b>{fmtGpa(t.sgpa)}</b></span>
                              <span>CGPA <b>{fmtGpa(t.cgpa)}</b></span>
                              <span>Term credits {t.term_credit_hours}</span>
                              <span>Cumulative {t.cumulative_credit_hours}</span>
                              {t.f_count_term > 0 ? (
                                <span className="text-[#a31a1a]">F count {t.f_count_term}</span>
                              ) : null}
                              <span className="text-[#5a5a5a]">
                                Authorised {fmtDate(t.authorised_at)}
                              </span>
                            </div>
                            {t.explanation ? (
                              <p className="mt-2 rounded-md bg-[#f6f9fc] px-3 py-2 text-[12.5px] text-[#3a3a3a]">
                                {t.explanation}
                              </p>
                            ) : null}
                          </div>
                        ))}
                      </div>
                    ) : (
                      <p className="mt-3 rounded-lg border border-dashed border-[#cfddec] bg-[#f6f9fc] px-4 py-8 text-center text-[13px] text-[#5a5a5a]">
                        No authorised standings yet. Your status appears here once the
                        department head authorises a term&apos;s grades.
                        {filingTermLabel ? ` Filing slip available for ${filingTermLabel}.` : ""}
                      </p>
                    )}
                  </>
                )}
              </div>
            </div>
          </section>
        </div>
      </main>
      <PortalFooter />
    </div>
  );
}
